name: Web UI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Chrome for Selenium
        uses: browser-actions/setup-chrome@v1

      - name: Grant Permission to Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Run Web UI Tests with Gradle
        run: ./gradlew clean test --no-daemon

      - name: Upload Web UI Test Report
        uses: actions/upload-artifact@v3
        with:
          name: web-ui-test-report
          path: build/reports/tests/test
       
