name: Web UI Tests for saucedemo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  web-ui-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set up Chrome for Selenium
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable


      - name: Run Web UI Tests with Gradle
        working-directory: ./untitled29
        run: ./gradlew clean test --no-daemon

      - name: Upload Web UI Test Report
        uses: actions/upload-artifact@v4
        with:
          name: web-ui-test-report
          path: build/reports/
